name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - run: flutter pub get
        
      #- run: flutter analyze
        
      - run: flutter test
      
      - run: flutter build apk --release
          
      - uses: actions/upload-artifact@v1
        with:
         name: nextmeal
         path: build/app/outputs/apk/release/app-release.apk
